### ISSUE TITLE
Harden prci when test def contains a wrong topology

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#227]
When a PR defines a wrong topology in a test definition, (for instance `topology: master_1repl_1client` instead of `topology: *master_1repl_1client`), PRCI crashes with the following trace:
```
Traceback (most recent call last):
   File "/root/freeipa-pr-ci/github/prci.py", line 307, in <module>
     main()
   File "/root/freeipa-pr-ci/github/prci.py", line 282, in main
     for task in process_pull_request(world, pull_request, repo_url):
   File "/root/freeipa-pr-ci/github/prci.py", line 122, in process_pull_request
     pull_request.author, repository_url, task_data, JobDispatcher
   File "/root/freeipa-pr-ci/github/internals/entities.py", line 575, in __init__
     self.topology = Topology.from_dict(topology_data)
   File "/root/freeipa-pr-ci/github/internals/entities.py", line 251, in from_dict
     name=dict_data.get("name"),
 AttributeError: 'str' object has no attribute 'get'
```

PRCI should be more robust. It could even set the 'postponed' label to the pull request so that the PR is not picked up for processing by other PR-CI runners, and add a message to the PR explaining the issue.

**Comment by flo-renaud** [comment]
Note: `topology: master_1repl_1client` is syntactically correct but prci is expecting a reference to a repeated node that will contain a dict.
