### ISSUE TITLE
Increase memory for client0 vms

### ISSUE THREAD

**Issue by netoarmando** [freeipa/freeipa-pr-ci#288]
`client0` vms failed more than once when collecting logs:
```python
/usr/lib/python3.7/site-packages/ipatests/pytest_ipa/integration/__init__.py:196: in integration_logs
collect_test_logs(request.node, class_integration_logs, request.config)
/usr/lib/python3.7/site-packages/ipatests/pytest_ipa/integration/__init__.py:72: in collect_test_logs
beakerlib_plugin=test_config.pluginmanager.getplugin('BeakerLibPlugin'),
/usr/lib/python3.7/site-packages/ipatests/pytest_ipa/integration/__init__.py:140: in collect_logs
cmd = host.run_command(['mktemp'])
``` 

For both cases topology `master_3repl_1client` was used to test `test_integration/test_nfs.py::TestNFS`.

Complete log: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e6deb456-981a-11e9-86ca-fa163e1e76f0/report.html

All other hosts are running with 2750MB of memory, while clients are running with 950MB:
https://github.com/freeipa/freeipa-pr-ci/blob/82296494adf96feff482ac4d8c0ed17bb261d199/templates/vagrantfiles/Vagrantfile.master_3repl_1client#L59-L63

This can be safely increased a little bit to solve this issue.

**Comment by netoarmando** [comment]
It can happen in paramiko as well:
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/d1b924f0-9854-11e9-83a9-5254006f8080/report.html

**Comment by fcami** [comment]
I think it can happen in master too:
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ee866714-98bd-11e9-a5cc-525400015176/report.html
```
transport.py               513 DEBUG    RUN ['kinit', 'admin']
transport.py               558 DEBUG    -bash: line 1: cd: /ipatests: No such file or directory
transport.py               558 DEBUG    -bash: line 2: /ipatests/env.sh: No such file or directory
transport.py               558 DEBUG    kinit: No more memory to allocate (in credentials cache code) while getting default ccache
```
and
```
transport.py               513 DEBUG    RUN ['ipa-server-install', '--uninstall', '-U', '--ignore-topology-disconnect', '--ignore-last-of-role']
transport.py               558 DEBUG    -bash: line 1: cd: /ipatests: No such file or directory
transport.py               558 DEBUG    -bash: line 2: /ipatests/env.sh: No such file or directory
transport.py               558 DEBUG    Traceback (most recent call last):
transport.py               558 DEBUG      File "/usr/sbin/ipa-server-install", line 23, in <module>
transport.py               558 DEBUG      File "/usr/lib/python3.7/site-packages/ipaserver/install/ipa_server_install.py", line 7, in <module>
transport.py               558 DEBUG      File "/usr/lib/python3.7/site-packages/ipapython/install/cli.py", line 11, in <module>
transport.py               558 DEBUG      File "/usr/lib64/python3.7/logging/__init__.py", line 28, in <module>
transport.py               558 DEBUG      File "/usr/lib64/python3.7/string.py", line 78, in <module>
transport.py               558 DEBUG      File "/usr/lib64/python3.7/string.py", line 75, in __init__
transport.py               558 DEBUG      File "/usr/lib64/python3.7/re.py", line 234, in compile
transport.py               558 DEBUG      File "/usr/lib64/python3.7/re.py", line 286, in _compile
transport.py               558 DEBUG        p = sre_compile.compile(pattern, flags)
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_compile.py", line 764, in compile
transport.py               558 DEBUG        p = sre_parse.parse(p, flags)
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 930, in parse
transport.py               558 DEBUG        p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 426, in _parse_sub
transport.py               558 DEBUG        not nested and not items))
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 816, in _parse
transport.py               558 DEBUG        p = _parse_sub(source, state, sub_verbose, nested + 1)
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 426, in _parse_sub
transport.py               558 DEBUG        not nested and not items))
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 816, in _parse
transport.py               558 DEBUG        p = _parse_sub(source, state, sub_verbose, nested + 1)
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 426, in _parse_sub
transport.py               558 DEBUG        not nested and not items))
transport.py               558 DEBUG      File "/usr/lib64/python3.7/sre_parse.py", line 816, in _parse
transport.py               558 DEBUG        p = _parse_sub(source, state, sub_verbose, nested + 1)
transport.py               558 DEBUG    MemoryError
transport.py               217 DEBUG    Exit code: 1
```

**Comment by netoarmando** [comment]
PR https://github.com/freeipa/freeipa-pr-ci/pull/289 increases the memory for client vms.

Since this happened with paramiko, I found this issue https://github.com/paramiko/paramiko/issues/949 that might be related.

**Comment by netoarmando** [comment]
PR @289 doesn't fix the problem. 

I tested 2 more times after the changes got merged and it failed again in one of the runs:
 - Failed run: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/830a8a52-9998-11e9-b6ce-fa163e00f31b/report.html
 - Succeeded run: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/84b965fe-999c-11e9-b6ce-fa163e00f31b/report.html

Since master and replica vms [experienced that](https://github.com/freeipa/freeipa-pr-ci/issues/288#issuecomment-506289797) too and they run with 2750MB I don't believe increase the available memory will fix this. Although it's safe to keep the current value.

**Comment by mulatinho** [comment]
Pardon if I am not able for enter on this discussion, but have you try to make a swapfile with about, hmmm, 4GB or just the double of memory allocated by vm to avoid problems with memory allocation? Perhaps this could help!

**Comment by netoarmando** [comment]
@mulatinho you are more than welcome here!
@fcami already told me to about that, it wasn't done yet because we were looking into paramilko first.

**Comment by netoarmando** [comment]
Closing this because #320 was merged.
