### ISSUE TITLE
prci-automation can't open a nightly PR without setting git user.name

### ISSUE THREAD

**Issue by netoarmando** [freeipa/freeipa-pr-ci#313]
When executing `open_close_pr.py` after a clean installation we get:
```
python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_f29 --repo_path /root/openclose_pr/freeipa --flow ci --branch master --prci_config ipatests/prci_definitions/nightly_f29.yaml --pr_against_upstream True
Running Open and Close PR Tool against freeipa-pr-ci/freeipa repo
Executing open_nightly_pr command
Older branch testing_f29 deleted in upstream
Traceback (most recent call last):
  File "/root/openclose_pr/open_close_pr.py", line 414, in <module>
    main()
  File "/root/openclose_pr/open_close_pr.py", line 410, in main
    automated_pr.run()
  File "/root/openclose_pr/open_close_pr.py", line 303, in run
    return fnc()
  File "/root/openclose_pr/open_close_pr.py", line 274, in open_nightly_pr
    self.commit_new_prci_config_file()
  File "/root/openclose_pr/open_close_pr.py", line 161, in commit_new_prci_config_file
    repo.git.commit('-m', DEFAULT_COMMIT_MSG)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m automated commit
  stderr: '
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@prci-automation.(none)')
```
Manually executing the following lines fixes the issue:
```
[root@prci-automation ~]# git config --global user.email "root"
[root@prci-automation ~]# git config --global user.name "root"
```

However, we should set that permanently using Ansible.

**Comment by netoarmando** [comment]
An addition to this error:
```bash
python3 /root/openclose_pr/open_close_pr.py open_nightly_pr --config /root/openclose_pr/config.yml --id testing_ipa-4.8 --repo_path /root/openclose_pr/freeipa --flow ci --branch ipa-4-8 --prci_config ipatests/prci_definitions/nightly_ipa-4-8.yaml --pr_against_upstream True
```
```python
Running Open and Close PR Tool against freeipa-pr-ci/freeipa repo
Executing open_nightly_pr command
Older branch testing_ipa-4.8 deleted in upstream
Traceback (most recent call last):
  File "/root/openclose_pr/open_close_pr.py", line 414, in <module>
    main()
  File "/root/openclose_pr/open_close_pr.py", line 410, in main
    automated_pr.run()
  File "/root/openclose_pr/open_close_pr.py", line 303, in run
    return fnc()
  File "/root/openclose_pr/open_close_pr.py", line 273, in open_nightly_pr
    self.rebase_branch()
  File "/root/openclose_pr/open_close_pr.py", line 236, in rebase_branch
    repo.git.checkout(self.args.branch)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout ipa-4-8
  stderr: 'error: pathspec 'ipa-4-8' did not match any file(s) known to git.'

```

**Comment by netoarmando** [comment]
Problem from description fixed by https://github.com/freeipa/freeipa-pr-ci/pull/315.
Error described in comment https://github.com/freeipa/freeipa-pr-ci/issues/313#issuecomment-538801535 was fixed by deploying the automation machine again.
