### ISSUE TITLE
Vagrant up fails with `require': cannot load such file -- winrm (LoadError) 

### ISSUE THREAD

**Issue by Gauravtalreja1** [freeipa/freeipa-pr-ci#331]
Issue: Vagrant up failing for winrm specific tests like test_smb and test_sssd , after upgrading runners to Fedora 30 ,

```
'2019-12-17 09:30:28,204     INFO  Executing: Process "vagrant up --no-provision --parallel"
2019-12-17 09:30:33,600    DEBUG  /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- winrm (LoadError)
2019-12-17 09:30:33,602    DEBUG  	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-12-17 09:30:33,602    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
2019-12-17 09:30:33,602    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
2019-12-17 09:30:33,602    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/registry.rb:27:in `get'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/machine.rb:259:in `communicate'
2019-12-17 09:30:33,603    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/machine.rb:141:in `initialize'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/vagrantfile.rb:81:in `new'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/vagrantfile.rb:81:in `machine'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/environment.rb:715:in `machine'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:186:in `each'
2019-12-17 09:30:33,604    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/plugins/commands/up/command.rb:87:in `execute'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/gems/vagrant-2.2.5/bin/vagrant:182:in `<top (required)>'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
2019-12-17 09:30:33,605    DEBUG  	from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
```
Runner logs,
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/dc971b5a-20af-11ea-b4d5-fa163e4bccbe/runner.log.gz
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/5c25e3e6-20d4-11ea-96b4-fa163e8ac44c/runner.log.gz

**Comment by netoarmando** [comment]
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1784787

**Comment by netoarmando** [comment]
Fixed in https://github.com/freeipa/freeipa-pr-ci/commit/8206e4a3d1e1009a17fbdee335789475d9344135.
