### ISSUE TITLE
runner crashes while watching PR queue

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#4]
```
Traceback (most recent call last):
  File "./prci.py", line 193, in <module>
    task.take(runner_id)
  File "/home/sharp/git/freeipa-pr-ci/github/prci_github/internals.py", line 219, in take
    status = Status(self.repo, self.pull, self.name)
  File "/home/sharp/git/freeipa-pr-ci/github/prci_github/internals.py", line 84, in __init__
    raise ValueError('No status with context {}'.format(context))
```

**Comment by tomaskrizek** [comment]
Resolved
