### ISSUE TITLE
PR-CI breaking when Github returns 422 Validation Failed

### ISSUE THREAD

**Issue by netoarmando** [freeipa/freeipa-pr-ci#412]
On Dec 19 2020 started to fail, printing:
```
Dec 21 18:24:20 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping testing-fedora/test_dns of #500: waiting for dependencies
Dec 21 18:24:20 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping testing-fedora/test_pwpolicy of #500: waiting for dependencies
Dec 21 18:24:20 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping fedora-27/simple_replication of #566: waiting for dependencies
Dec 21 18:24:20 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping PR#569: can't be merged
Dec 21 18:24:20 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping testing-fedora/test_installation_client of #594: not enough resources
Dec 21 18:24:21 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping fedora-rawhide/test_installation_TestInstallWithCA_KRA_DNS1 of #600: not enough resources
Dec 21 18:24:21 permanent-small-runner-0 bash[8888]: INFO: __main__: Skipping fedora-rawhide/test_idviews of #600: not enough resources
Dec 21 18:24:21 permanent-small-runner-0 bash[8888]: INFO: __main__: Attempting to lock a task fedora-rawhide/test_ipahealthcheck for PR#600.
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]: Traceback (most recent call last):
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/prci.py", line 322, in <module>
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     main()
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/prci.py", line 295, in main
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     for task in process_pull_request(world, pull_request, repo_url):
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/prci.py", line 158, in process_pull_request
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     task = process_task(world, task, pull_request.commit.statuses)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/prci.py", line 220, in process_task
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     task.lock(world)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/internals/entities.py", line 681, in lock
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     world.create_status(self, State.PENDING, description)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/root/freeipa-pr-ci/github/internals/entities.py", line 205, in create_status
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     self.github_api.repository(
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/usr/local/lib/python3.8/site-packages/github3/decorators.py", line 31, in auth_wrapper
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     return func(self, *args, **kwargs)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/usr/local/lib/python3.8/site-packages/github3/repos/repo.py", line 1240, in create_status
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     json = self._json(self._post(url, data=data), 201)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:   File "/usr/local/lib/python3.8/site-packages/github3/models.py", line 156, in _json
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]:     raise exceptions.error_for(response)
Dec 21 18:24:30 permanent-small-runner-0 bash[8888]: github3.exceptions.UnprocessableEntity: 422 Validation Failed
Dec 21 18:24:30 permanent-small-runner-0 systemd[1]: prci.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 18:24:30 permanent-small-runner-0 systemd[1]: prci.service: Failed with result 'exit-code'.
Dec 21 18:24:30 permanent-small-runner-0 systemd[1]: prci.service: Consumed 2.440s CPU time.
Dec 21 18:27:30 permanent-small-runner-0 systemd[1]: prci.service: Scheduled restart job, restart counter is at 37.
Dec 21 18:27:30 permanent-small-runner-0 systemd[1]: Stopped FreeIPA PR CI.
Dec 21 18:27:30 permanent-small-runner-0 systemd[1]: prci.service: Consumed 2.440s CPU time.
Dec 21 18:27:30 permanent-small-runner-0 systemd[1]: Started FreeIPA PR CI.
Dec 21 18:27:31 permanent-small-runner-0 bash[8894]: INFO: __main__: Checking pending pull requests.
```
The response from Github API for job breaking the service was:
```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Status",
      "code": "custom",
      "message": "This SHA and context has reached the maximum number of statuses."
    }
  ],
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-commit-status"
}
```
That job had 1000 statuses set from `2020-12-19 11:50 UTC` to `2020-12-19 13:13 UTC`
![Screenshot from 2020-12-21 15-31-40](https://user-images.githubusercontent.com/217367/102809976-add2c880-43a1-11eb-808e-4528ffa72fbe.png)

Later that day Github reported an incident with pull requests: https://www.githubstatus.com/incidents/w5mwfprfbzzy (not sure if that can be related)

### Workaround
- **Option 1**: Force push a new commit the pull request breaking PR-CI, statuses will be created for a new hash.
- **Option 2**: Close PR

**Comment by netoarmando** [comment]
cc: @bhavikbhavsar
