### ISSUE TITLE
Some jobs fail at provisioning (?) and then timeout

### ISSUE THREAD

**Issue by fcami** [freeipa/freeipa-pr-ci#420]
See:
https://github.com/freeipa-pr-ci2/freeipa/pull/721#issuecomment-781414443
[log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0b909356-714e-11eb-ad42-fa163e0817f7/)
```
2021-02-17 19:12:43,953    DEBUG  skipping: [ad-tree]
2021-02-17 19:12:44,073    DEBUG  skipping: [ad-child]
2021-02-17 19:12:44,120    DEBUG  skipping: [ad-root]
2021-02-17 19:49:18,054 CRITICAL  Terminating execution, runtime exceeded 4800s
2021-02-17 19:49:18,079 CRITICAL  No free disk space
2021-02-17 19:49:18,115    DEBUG  Process "vagrant provision" exited with error code -9
Traceback (most recent call last):
  File "/root/freeipa-pr-ci/tasks/common.py", line 135, in __call__
    super(FallibleTask, self).__call__()
  File "/root/freeipa-pr-ci/tasks/common.py", line 122, in __call__
    raise self.exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 105, in __target
    self._run()
  File "/root/freeipa-pr-ci/tasks/common.py", line 179, in _run
    raise PopenException(self)
tasks.common.PopenException: Process "vagrant provision" exited with error code -9
```

**Comment by fcami** [comment]
What causes this is unclear, but it seems to only happen with AD jobs.
Still, this was triggered by a lot of AD jobs on two different nightlies this week, with the same trace.

**Comment by fcami** [comment]
@netoarmando I've just realized one thing, these all fail at the updates step:
```
2021-02-21 06:36:15,953    DEBUG  TASK [machine/provision : update packages] *************************************
2021-02-21 06:36:16,018    DEBUG  skipping: [ad-tree]
2021-02-21 06:36:16,057    DEBUG  skipping: [ad-child]
2021-02-21 06:36:16,101    DEBUG  skipping: [ad-root]
2021-02-21 08:27:23,168 CRITICAL  Terminating execution, runtime exceeded 9000s
2021-02-21 08:27:23,218 CRITICAL  No free disk space
2021-02-21 08:27:23,245    DEBUG  Process "vagrant provision" exited with error code -9
```
and this only happens to the "testing" jobs e.g. with updates-testing.

**Comment by netoarmando** [comment]
> and this only happens to the "testing" jobs e.g. with updates-testing.

Nice find, so I think these boxes are a little bit old, I'll update them, it seems that having the packages updated might fix this.

**Comment by wladich** [comment]
As all issues related to disk space are currently resolved I propose to close the issue.
