### ISSUE TITLE
freeipa-pr-ci fails to run tests on rawhide machines

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#491]
### Issue
The nightly tests are failing on rawhide, see PR [2812](https://github.com/freeipa-pr-ci2/freeipa/pull/2812) with for instance the test `automember` ([runner.log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/617b9f5a-1d80-11ee-ae06-fa163e237cdd/runner.log.gz)).

The runners are fedora 32 machines. On the runner, freeipa-pr-ci creates Vagrant machines for the controller/server/replicas/clients and the [Vagrantfile](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/617b9f5a-1d80-11ee-ae06-fa163e237cdd/Vagrantfile) runs an ansible playbook:
```
    config.vm.define "controller" , primary: true do |controller|
        controller.vm.provider "libvirt" do |domain,override|
            # Less resources needed for controller - same amount as the clients
            domain.memory = 1250
        end

        controller.vm.provision :ansible do |ansible|
            # Disable default limit to connect to all the machines
            ansible.limit = "all"
            ansible.playbook = "../../ansible/provision.yml"
            ansible.extra_vars = "vars.yml"
        end
    end
```

When the Vagrant machine is rawhide, the ansible playbook cannot be executed, the [runner.log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/617b9f5a-1d80-11ee-ae06-fa163e237cdd/runner.log.gz) shows an issue with one of the ansible modules:
```
2023-07-08 11:19:13,333    DEBUG  TASK [machine/provision : update pip packages] *********************************
2023-07-08 11:19:14,308    DEBUG  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
2023-07-08 11:19:14,309    DEBUG  fatal: [master]: FAILED! => {
2023-07-08 11:19:14,310    DEBUG      "changed": false,
2023-07-08 11:19:14,310    DEBUG      "rc": 1
2023-07-08 11:19:14,310    DEBUG  }
2023-07-08 11:19:14,310    DEBUG  
2023-07-08 11:19:14,310    DEBUG  MSG:
2023-07-08 11:19:14,310    DEBUG  
2023-07-08 11:19:14,310    DEBUG  MODULE FAILURE
2023-07-08 11:19:14,310    DEBUG  See stdout/stderr for the exact error
2023-07-08 11:19:14,310    DEBUG  
2023-07-08 11:19:14,310    DEBUG  
2023-07-08 11:19:14,310    DEBUG  MODULE_STDOUT:
2023-07-08 11:19:14,311    DEBUG  
2023-07-08 11:19:14,311    DEBUG  Traceback (most recent call last):
2023-07-08 11:19:14,312    DEBUG    File "/root/.ansible/tmp/ansible-tmp-1688815153.492237-4064126-57801784529359/AnsiballZ_pip.py", line 102, in <module>
2023-07-08 11:19:14,312    DEBUG      _ansiballz_main()
2023-07-08 11:19:14,312    DEBUG    File "/root/.ansible/tmp/ansible-tmp-1688815153.492237-4064126-57801784529359/AnsiballZ_pip.py", line 94, in _ansiballz_main
2023-07-08 11:19:14,313    DEBUG      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
2023-07-08 11:19:14,313    DEBUG    File "/root/.ansible/tmp/ansible-tmp-1688815153.492237-4064126-57801784529359/AnsiballZ_pip.py", line 37, in invoke_module
2023-07-08 11:19:14,313    DEBUG      from ansible.module_utils import basic
2023-07-08 11:19:14,313    DEBUG    File "/tmp/ansible_pip_payload_urd7z5di/ansible_pip_payload.zip/ansible/module_utils/basic.py", line 173, in <module>
2023-07-08 11:19:14,313    DEBUG  ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
```

This is probably linked to the recent update of ansible to 8.1.0 and ansible-core to 2.15.1 on rawhide ([bodhi link](https://bodhi.fedoraproject.org/updates/FEDORA-2023-f1c810932f)).

**Comment by flo-renaud** [comment]
FYI @pvoborni @kaleemsiddiqu

**Comment by flo-renaud** [comment]
The runners are deployed on fedora 32 with an old version of ansible (2.9.13-1). When freeipa-pr-ci picks up a test suite, it starts vagrant machines and the Vagrant file is using an ansible provisioner.
The ansible provisioner prepares the modules as zip files using the local python code (from ansible 2.9.13-1, python3-3.8.5-5 and python3-six-1.14.0-2), copies the zip on the vagrant machine (which is rawhide) and tries to execute the remote module.
The runner and the rawhide machines have versions that do not work together. There were simply too many code changes between those versions.

We need to upgrade the runners to a more recent version. I tested with a Fedora 37 runner and the integration test looks ok. Need to check if the webui tests are also working.

**Comment by flo-renaud** [comment]
The webui tests need to execute with selenium 4.9.0 but otherwise f37 seems a good choice.

**Comment by flo-renaud** [comment]
Fixed with the migration to f39 runners
