### ISSUE TITLE
runner crashes while watching PR queue #2

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#5]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib64/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib64/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./prci.py", line 193, in <module>
    task.take(runner_id)
  File "/home/sharp/git/freeipa-pr-ci/github/prci_github/internals.py", line 219, in take
    status = Status(self.repo, self.pull, self.name)
  File "/home/sharp/git/freeipa-pr-ci/github/prci_github/internals.py", line 80, in __init__
    for status in repo.commit(pull.pull.head.sha).statuses():
  File "/usr/lib/python3.5/site-packages/github3/repos/repo.py", line 487, in commit
    json = self._json(self._get(url), 200)
  File "/usr/lib/python3.5/site-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.5/site-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/sharp/git/freeipa-pr-ci/github/prci_github/adapter.py", line 36, in send
    request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/cachecontrol/adapter.py", line 50, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by tomaskrizek** [comment]
The error most likely happened when a re-run label was being handled. Jobs appear to have been created and one of them was probably assigned to the runner before the crash.

**Comment by tomaskrizek** [comment]
Encountered again

**Comment by tomaskrizek** [comment]
This doesn't seem to happen any more. If it does, it will be caught by sentry and it won't cause a crash of the runner any more.
